--- Starting bitbake server pid 38415 at 2020-05-07 05:45:11.338518 ---
ERROR: Traceback (most recent call last):
  File "/home/nano/jetson-nano/sources/poky/bitbake/lib/bb/cookerdata.py", line 170, in wrapped
    return func(fn, *args)
  File "/home/nano/jetson-nano/sources/poky/bitbake/lib/bb/cookerdata.py", line 195, in parse_config_file
    return bb.parse.handle(fn, data, include)
  File "/home/nano/jetson-nano/sources/poky/bitbake/lib/bb/parse/__init__.py", line 107, in handle
    return h['handle'](fn, data, include)
  File "/home/nano/jetson-nano/sources/poky/bitbake/lib/bb/parse/parse_py/ConfHandler.py", line 124, in handle
    abs_fn = resolve_file(fn, data)
  File "/home/nano/jetson-nano/sources/poky/bitbake/lib/bb/parse/__init__.py", line 131, in resolve_file
    raise IOError(errno.ENOENT, "file %s not found" % fn)
FileNotFoundError: [Errno 2] file /home/nano/jetson-nano/build/../sources/openembedded-core/conf/layer.conf not found

ERROR: Unable to parse /home/nano/jetson-nano/build/../sources/openembedded-core/conf/layer.conf: [Errno 2] file /home/nano/jetson-nano/build/../sources/openembedded-core/conf/layer.conf not found
